# entities/dca.py
from __future__ import annotations

import hashlib
import random
import time
from dataclasses import dataclass
from typing import List, Tuple

from core.shamir import split_secret, recover_secret


@dataclass
class DCAMember:
    member_id: int
    share_x: int
    share_y: int

    def issue_registration_share(self, uav_seed: int, prime: int) -> Tuple[int, int]:
        """
        Partial registration credential:
            partial_credential = share_y * uav_seed mod prime
        """
        partial_credential = (self.share_y * uav_seed) % prime
        return self.share_x, partial_credential

    def issue_cross_domain_share(
        self,
        target_domain_seed: int,
        delta_value: int,
        prime: int,
    ) -> Tuple[int, int]:
        """
        Partial cross-domain token share:
            partial_token = share_y * target_domain_seed * delta_value mod prime
        """
        partial_token = (self.share_y * target_domain_seed * delta_value) % prime
        return self.share_x, partial_token


@dataclass
class CrossDomainToken:
    source_domain: str
    target_domain: str
    validity_until: int
    delta_digest: str
    token_value: int

    def summary(self) -> str:
        return (
            f"CrossDomainToken("
            f"source={self.source_domain}, "
            f"target={self.target_domain}, "
            f"validity_until={self.validity_until}, "
            f"delta_digest={self.delta_digest[:16]}..., "
            f"token_value={self.token_value})"
        )


class DCACluster:
    def __init__(self, domain_id: str, n: int, t: int, prime: int):
        self.domain_id = domain_id
        self.n = n
        self.t = t
        self.prime = prime

        self.domain_secret = random.randrange(1, prime)
        self.delta_value = random.randrange(1, prime)  # out-of-domain issuance discriminator
        self.members: List[DCAMember] = []

        self._setup_members()

    def _setup_members(self) -> None:
        shares = split_secret(self.domain_secret, self.n, self.t, self.prime)
        for idx, (x, y) in enumerate(shares, start=1):
            self.members.append(DCAMember(member_id=idx, share_x=x, share_y=y))

    def get_available_members(self, count: int) -> List[DCAMember]:
        return self.members[:count]

    def issue_registration_shares(self, uav_seed: int, available_count: int) -> List[Tuple[int, int]]:
        available_members = self.get_available_members(available_count)
        return [member.issue_registration_share(uav_seed, self.prime) for member in available_members]

    def build_target_domain_seed(self, target_domain: str) -> int:
        raw = f"{self.domain_id}->{target_domain}"
        digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()
        return int(digest, 16) % self.prime

    def delta_digest(self) -> str:
        return hashlib.sha256(str(self.delta_value).encode("utf-8")).hexdigest()

    def generate_cross_domain_token(
        self,
        target_domain: str,
        available_count: int,
        validity_period: int = 300,
    ) -> CrossDomainToken | None:
        """
        Generate a cross-domain token from source domain self.domain_id to target_domain.
        Requires at least t available DCA members.
        """
        if available_count < self.t:
            return None

        target_domain_seed = self.build_target_domain_seed(target_domain)
        available_members = self.get_available_members(available_count)

        partial_shares = [
            member.issue_cross_domain_share(
                target_domain_seed=target_domain_seed,
                delta_value=self.delta_value,
                prime=self.prime,
            )
            for member in available_members
        ]

        token_value = recover_secret(partial_shares[:self.t], self.prime)

        return CrossDomainToken(
            source_domain=self.domain_id,
            target_domain=target_domain,
            validity_until=int(time.time()) + validity_period,
            delta_digest=self.delta_digest(),
            token_value=token_value,
        )

    def verify_cross_domain_token(
        self,
        token: CrossDomainToken,
        source_dca: "DCACluster",
        now_ts: int | None = None,
    ) -> bool:
        """
        A target-domain DCA verifies whether token was correctly generated by source_dca.
        """
        if now_ts is None:
            now_ts = int(time.time())

        if token.source_domain != source_dca.domain_id:
            return False

        if token.target_domain != self.domain_id:
            return False

        if now_ts > token.validity_until:
            return False

        if token.delta_digest != source_dca.delta_digest():
            return False

        expected_seed = source_dca.build_target_domain_seed(self.domain_id)
        expected_value = (source_dca.domain_secret * expected_seed * source_dca.delta_value) % self.prime

        return expected_value == token.token_value
